In [1]:
import torch

from torch import nn


model = nn.Linear(in_features=10, out_features=5)
print("Весовой тензор W:", model.weight.shape)   # torch.Size([5, 10])
print("Вектор смещений b:", model.bias.shape)    # torch.Size([5])


# Проверим, что по умолчанию требуется вычисление градиентов
print(model.weight.requires_grad)
print(model.bias.requires_grad) 

Весовой тензор W: torch.Size([5, 10])
Вектор смещений b: torch.Size([5])
True
True


In [2]:
import torch

from torch import nn


relu = nn.ReLU()
x = torch.tensor([[-1.0, 0.0, 2.0], [3.0, -5.0, 1.0]])
y = relu(x)
print(y)

tensor([[0., 0., 2.],
        [3., 0., 1.]])


In [3]:
import torch

from torch import nn


# Предположим, что мы уже создали в __init__ следующие слои:
fc1 = nn.Linear(10, 5)     # из 10 входов в 5 нейронов
relu = nn.ReLU()
fc2 = nn.Linear(5, 1)      # из 5 входов в 1 нейрон


# А вот упрощённая функция forward, написанная вне класса:
def forward_pass(x):
    x1 = fc1(x)            # применили первый линейный слой
    x2 = relu(x1)          # применили ReLU
    x3 = fc2(x2)           # применили второй линейный слой
    return x3


# Создадим тестовый входной батч: batch_size=3, in_features=10

input_tensor = torch.randn(3, 10)
output_tensor = forward_pass(input_tensor)
print(input_tensor)
print(output_tensor)  # tensor of shape [3, 1]

tensor([[-0.6415,  0.9305,  0.4392,  0.0948,  0.2760,  1.4427,  0.2083,  0.9558,
         -1.1138, -0.6944],
        [ 0.1772, -0.8668,  0.4815,  1.6942,  0.6127,  0.5258,  0.0478, -1.3276,
         -0.6619, -0.4524],
        [ 1.3828, -1.1464,  1.6925,  1.7454,  0.5877, -0.3209, -1.2121,  0.4727,
         -1.2712, -0.3615]])
tensor([[-0.4203],
        [-0.9235],
        [-0.9316]], grad_fn=<AddmmBackward0>)


In [7]:
class SimpleNN(nn.Module):
    def __init__(self):
        # Базовая инициализация nn.Module
        # Ваш код здесь
        super().__init__()
        # Линейный слой: принимает тензор размера [..., 10], выдаёт [..., 5]
        # Ваш код здесь
        self.fc1 = nn.Linear(10, 5)
        # Функция активации ReLU
        # Ваш код здесь
        self.relu = nn.ReLU()
        # Линейный слой: принимает [..., 5], выдаёт [..., 1]
        # Ваш код здесь
        self.fc2 = nn.Linear(5, 1)


    def forward(self, x):
        # x - тензор размерности [batch_size, 10]
        x = self.fc1(x)          # теперь x → [batch_size, 5]
        # Примените ReLU
        x = self.relu(x)
        # Линейный слой x → [batch_size, 1]      
        x = self.fc2(x)
        return x                 # возвращаем тензор прогнозов


# Пример использования:
model = SimpleNN()
print(model)


# Можно сразу посмотреть, сколько параметров зарегистрировано:
total_params = sum(p.numel() for p in model.parameters())
print(f"Всего параметров: {total_params}") 

SimpleNN(
  (fc1): Linear(in_features=10, out_features=5, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=5, out_features=1, bias=True)
)
Всего параметров: 61


In [8]:

from torch.utils.data import Dataset


class MyDataset(Dataset):
    def __init__(self, data, targets):
        self.data = data
        self.targets = targets


    def __len__(self):
        return len(self.data)


    def __getitem__(self, idx):
        return self.data[idx], self.targets[idx]


# Создадим датасет из списков чисел
dataset = MyDataset(data=list(range(10)), targets=[2*x for x in range(10)])
print(len(dataset), dataset[0])  # 10, (0, 0)
print(dataset[1])            

10 (0, 0)
(1, 2)


In [9]:

from torch.utils.data import DataLoader


class MyDataset(Dataset):
    def __init__(self, data, targets):
        self.data = data
        self.targets = targets


    def __len__(self):
        return len(self.data)


    def __getitem__(self, idx):
        return self.data[idx], self.targets[idx]


# Создадим датасет из списков чисел
dataset = MyDataset(data=list(range(10)), targets=[2*x for x in range(10)])


dataloader = DataLoader(dataset, batch_size=3, shuffle=True, num_workers=0)
for batch_data, batch_target in dataloader:
    print(batch_data, batch_target)
    break  # посмотрим только первый батч

tensor([3, 7, 0]) tensor([ 6, 14,  0])


In [10]:

# 1. Реализуйте класс ToyDataset

class ToyDataset(Dataset):
    def __init__(self, data, targets):
        # Сохраните data и targets в атрибуты
        # Ваш код здесь
        self.data = data
        self.targets = targets
        pass


    def __len__(self):
        # Верните длину датасета
        # Ваш код здесь
        return len(self.data)
        


    def __getitem__(self, idx):
        # Верните пару (вход, метка), соответствующую индексу idx
        # Ваш код здесь
        return self.data[idx], self.targets[idx]
        pass


# 2. Подготовьте входные списки
raw_data = list(range(10)) # data = [0, 1, 2, ..., 9]
raw_targets = [2 * x for x in raw_data]  # targets = [0, 2, 4, ..., 18]


# 3. Создайте объект ToyDataset

dataset = ToyDataset(data = raw_data, targets = raw_targets)


# 4. Оберните датасет в DataLoader с batch_size=4 и shuffle=True

dataloader = DataLoader(dataset, batch_size=4, shuffle=True, num_workers=0)


# Переберите первые два батча и выведите их на экран
for batch_idx, (batch_inputs, batch_targets) in enumerate(dataloader):
    print(f"Батч {batch_idx + 1}:")
    print("Inputs: ", batch_inputs)
    print("Targets:", batch_targets)
    if batch_idx == 1:  # остановимся после второго батча
        break

Батч 1:
Inputs:  tensor([6, 0, 7, 8])
Targets: tensor([12,  0, 14, 16])
Батч 2:
Inputs:  tensor([5, 1, 9, 2])
Targets: tensor([10,  2, 18,  4])


In [11]:
# 1. Определяем класс SimpleNN

class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()  
        # Линейный слой: 5 нейронов на скрытом слое
        self.fc1 = nn.Linear(in_features=5, out_features=5)
        # ReLU-активация
        self.relu = nn.ReLU()
        # Выходной слой: 1 нейрон
        self.fc2 = nn.Linear(in_features=5, out_features=1)


    def forward(self, x):
        # x: [batch_size, 5]
        x = self.fc1(x)      # -> [batch_size, 5]
        x = self.relu(x)     # -> [batch_size, 5]
        x = self.fc2(x)      # -> [batch_size, 1]
        return x


# 2. Создаём модель и оптимизатор
model = SimpleNN()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
criterion = nn.MSELoss()


# 3. Генерируем случайные входные данные и метки
torch.manual_seed(0)
X = torch.randn(3, 5)
y = torch.randn(3, 1)


# 4. Сохраняем веса первого слоя до обучения
weights_before = model.fc1.weight.clone()


# 5. Прямой проход и вычисление лосса
outputs = model(X)
loss = criterion(outputs, y)


# 6. Шаг обучения
optimizer.zero_grad()
loss.backward()
optimizer.step()


# 7. Сохраняем веса первого слоя после обучения
weights_after = model.fc1.weight


# 8. Выводим кусочек весов до и после, а также значение loss

print("Весовой тензор fc1.weight до обучения (кусочек):")
print(weights_before[:2, :3])
print("\nВесовой тензор fc1.weight после обучения (кусочек):")
print(weights_after[:2, :3])
print(f"\nЗначение лосса: {loss.item():.4f}")

Весовой тензор fc1.weight до обучения (кусочек):
tensor([[ 0.0483, -0.1087, -0.1647],
        [ 0.2285, -0.1719,  0.1463]], grad_fn=<SliceBackward0>)

Весовой тензор fc1.weight после обучения (кусочек):
tensor([[ 0.0483, -0.1087, -0.1647],
        [ 0.2278, -0.1717,  0.1466]], grad_fn=<SliceBackward0>)

Значение лосса: 0.1882


In [15]:

import matplotlib.pyplot as plt

import torchvision.transforms as transforms

from torchvision.datasets import MNIST


transform = transforms.Compose([
    transforms.ToTensor(),                     # из [0,255] в [0,1]
    transforms.Normalize((0.1307,), (0.3081,)) # нормализация (mean=0.1307,std=0.3081)
])


train_data = MNIST(root='./data', train=True, download=True, transform=transform)
test_data  = MNIST(root='./data', train=False, download=True, transform=transform)


# Блок кода, отвечающий за визуализацию, его редактировать не надо.
fig, axes = plt.subplots(1, 5, figsize=(10,2))
for i, ax in enumerate(axes):
    img, label = train_data[i]
    ax.imshow(img.squeeze(), cmap='gray')
    ax.set_title(f"Label: {label}")
    ax.axis('off')
plt.show()

RuntimeError: operator torchvision::nms does not exist